/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.novo.views;

import com.novo.models.Mover;
import java.awt.Color;
import java.awt.Panel;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.SwingUtilities;
import sun.awt.windows.ThemeReader;

/**
 *
 * @author HMARTINEZ
 */
public class EtiquetaPanel extends javax.swing.JPanel {

    /**
     * Creates new form EtiquetaPanel
     */
    private int elementoAsignar;
    private String textAsignar;
    private JTextField textField;
    private JTextArea textField2;
    private Runnable monitor;
        Mover mml;
   // JLabel movimiento = new JLabel();

    public EtiquetaPanel() {
        initComponents();
        
                mml = new Mover(jPanel1);
    jPanel1.addMouseListener(mml);
    jPanel1.addMouseMotionListener(mml);
        
             
        
    }

    public JLabel getlContenido() {
        return lContenido;
    }

    public void setlContenido(JLabel lContenido) {
        this.lContenido = lContenido;
    }

    public JLabel getlFechaC() {
        return lFechaC;
    }

    public void setlFechaC(JLabel lFechaC) {
        this.lFechaC = lFechaC;
    }

    public JLabel getlTitulo() {
        return lTitulo;
    }

    public void setlTitulo(JLabel lTitulo) {
        this.lTitulo = lTitulo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        lFechaC = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lTitulo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lContenido = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 255, 153));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        jPanel1.setBackground(new Color(0,0,0,0));

        lFechaC.setBackground(new Color(0,0,0,0));
        lFechaC.setText(new SimpleDateFormat("dd/MM/yy").format(new Date()));
        lFechaC.setName("lFechaC"); // NOI18N

        jPanel2.setBackground(new Color(0,0,0,0));
        jPanel2.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel2.setPreferredSize(new java.awt.Dimension(281, 18));
        jPanel2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel2FocusLost(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });

        lTitulo.setBackground(new Color(0,0,0,0));
        lTitulo.setText("jLabel3");
        lTitulo.setName("lTitulo"); // NOI18N
        lTitulo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lTituloMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        lTitulo.getAccessibleContext().setAccessibleName("lTitulo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(lFechaC, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(lFechaC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lFechaC.getAccessibleContext().setAccessibleName("lFechaC");

        jPanel3.setBackground(new Color(0,0,0,0));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jPanel3FocusLost(evt);
            }
        });
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        lContenido.setBackground(new Color(0,0,0,125));
        lContenido.setText("jLabel4");
        lContenido.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        lContenido.setName("lContenido"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lContenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lContenido, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        lContenido.getAccessibleContext().setAccessibleName("lContenido");

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 15, Short.MAX_VALUE)
        );

        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel6MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 18, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lTituloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lTituloMouseClicked

        int posX = this.getlTitulo().getX();
        int posY = this.getlTitulo().getY();

        //JTextField textField = new JTextField();
        textField = new JTextField();

        textField.setBorder(null);
       // textField.requestFocus();
        //textField.selectAll();
        //textField.setLayout(this.getlTitulo().getLayout());
        //textField.setAlignmentX(posX);
        //textField.setAlignmentY(posY);

        textField.setBounds(this.getlTitulo().getBounds());
        textField.setText(lTitulo.getText());
        textField.setVisible(true);
        elementoAsignar = this.getlTitulo().getComponentCount();
       // System.out.println(this.getlTitulo().getName());

    //this.getLayout().addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
      //  this.add(textField);
        //  this.repaint();
        //   this.validate();
        this.add(textField);
        //textField.setSize(250, 25);
        System.out.println("PosX: " + posX + ", PosY: " + posY);
        textField.setBounds(posX, posY - 5, this.getWidth() - 150, 37);
        textField.setBackground(null);

        this.getlTitulo().setVisible(false);

        /*    textField.addFocusListener(new FocusListener() {
         public void focusGained(FocusEvent e) {
         e.getComponent().setBackground(Color.RED);
         // e.getOpositeComponent() devuelve el Component que le
         // cede el foco a nuestro botón.
         }
         public void focusLost(FocusEvent e) {
         e.getComponent().setBackground(Color.BLACK);
         // get.OpositeComponent() devuelve el Component al que
         // nuestro botón cede el foco.
         }
         }); */
        textField.requestFocus();

        textField.setSelectionStart(0);
        textField.setSelectionEnd(textField.getText().length());

        this.updateUI();
     //   this.repaint();

        //this.validate();
        // TODO add your handling code here:
    }//GEN-LAST:event_lTituloMouseClicked

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked

        //textField.setVisible(false);
        //System.out.println(this.getComponent(elementoAsignar).getName());
        if (textField != null) {
            lTitulo.setText(textField.getText());
            lTitulo.setVisible(true);
            textField.setVisible(false);
            textField = null;
            this.repaint();
        }

        jPanel3FocusLost(null);

        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:

        this.lTituloMouseClicked(evt);


    }//GEN-LAST:event_jPanel2MouseClicked

    private void jPanel2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel2FocusLost
        // TODO add your handling code here:
        this.formMouseClicked(null);

    }//GEN-LAST:event_jPanel2FocusLost

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2 && textField2 == null) {
            int posX = this.getlContenido().getX();
            int posY = jPanel3.getY();

      //  System.out.println(jPanel3.getY());
            //JTextField textField = new JTextField();
            textField2 = new JTextArea();

            textField2.setBorder(null);
       // textField.requestFocus();
            //textField.selectAll();
            //textField.setLayout(this.getlTitulo().getLayout());
            //textField.setAlignmentX(posX);
            //textField.setAlignmentY(posY);

            textField2.setBounds(this.getlContenido().getBounds());
            textField2.setText(lContenido.getText());
            textField2.setVisible(true);
            elementoAsignar = this.getlContenido().getComponentCount();
       // System.out.println(this.getlTitulo().getName());

    //this.getLayout().addComponent(textField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE);
      //  this.add(textField);
            //  this.repaint();
            //   this.validate();
            this.add(textField2);
            //textField.setSize(250, 25);
            System.out.println("PosX: " + posX + ", PosY: " + posY);
            textField2.setBounds(posX, posY - 10, this.getWidth() - 150, this.getHeight() - 50);
            textField2.setBackground(null);

            this.getlContenido().setVisible(false);

            /*    textField.addFocusListener(new FocusListener() {
             public void focusGained(FocusEvent e) {
             e.getComponent().setBackground(Color.RED);
             // e.getOpositeComponent() devuelve el Component que le
             // cede el foco a nuestro botón.
             }
             public void focusLost(FocusEvent e) {
             e.getComponent().setBackground(Color.BLACK);
             // get.OpositeComponent() devuelve el Component al que
             // nuestro botón cede el foco.
             }
             }); */
            textField2.requestFocus();

            textField2.setSelectionStart(0);
            textField2.setSelectionEnd(textField2.getText().length());

            this.updateUI();
            //   this.repaint();
        } else {

            jPanel3FocusLost(null);
            formMouseClicked(null);
        }


    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusLost
        // TODO add your handling code here:
        System.out.println("Salida de panel 3");

        if (textField2 != null) {

            String texto = textField2.getText();

            texto = texto.replaceAll("\n", "<br>");
            lContenido.setText("<html>"+texto+"</html>");
            lContenido.setVisible(true);
            textField2.setVisible(false);
            textField2 = null;
            this.repaint();
        }
             //     textField2.setVisible(false);

    }//GEN-LAST:event_jPanel3FocusLost

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        System.out.println("Color");
        PaletaPanel paletaPanel = PaletaPanel.getInstance();
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
       // JDialog frame = new PaletaFrame(topFrame, false);
        PaletaFrame frame = PaletaFrame.getInstance();
        PaletaFrame.getInstance().setEtiquetaPanel(this);
        //frame.setUndecorated(true);
        //frame.setVisible(true);
        
        paletaPanel.setVisible(true);

        paletaPanel.setBounds(lContenido.getBounds());
        frame.add(paletaPanel);
        
        frame.setAlwaysOnTop(true);
        frame.setResizable(false);
        frame.setModal(true);
        frame.setLocationRelativeTo(jPanel4);
        paletaPanel.setBounds(0, 0, 147, 84);
        System.out.println("W: " + paletaPanel.getWidth() + " H: " + paletaPanel.getHeight());
        frame.setSize(paletaPanel.getWidth(), paletaPanel.getHeight());
       // frame.pack();
        frame.validate();
        frame.repaint();
        frame.setVisible(true);
        //frame.setMaximumSize(frame.getSize());
        this.validate();
        this.repaint();
        
        

    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseClicked
        // TODO add your handling code here:
        
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        
        topFrame.dispose();
        
        
        
    }//GEN-LAST:event_jPanel6MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lContenido;
    private javax.swing.JLabel lFechaC;
    private javax.swing.JLabel lTitulo;
    // End of variables declaration//GEN-END:variables
}
